version: '3.9'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

  redis:
    image: redis/redis-stack:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"     # Redis server port
      - "8001:8001"     # Redis GUI web interface port
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
